# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0c176faa59c97c4a7cc50a2bbf1f8e34514d12d1c72de7b5f3d458a2ecb82d8a8c2de63151d4b952948944a94bcacc05959d10ace0e2afca7d412ae50f499d9

test:
  secret_key_base: 1149501132862ceb17419e4e41a0b65440436f1dbb42ca4ea555a58f941ef0d66113239dcbd8e34161d55cc3af949c53e7c569ad7bc4de95ec5fbc2387925b67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
